baseurl = "https://tellmey18.github.io/indexofnitc/ "
languageCode = "en-us"
theme = "terminal"
paginate = 5

[params]
  contentTypeName = "posts"
  themeColor = "orange"
  showMenuItems = 5 
  fullWidthTheme = true
  centerTheme = false

[languages]
  [languages.en]
    title = "Terminal"
    subtitle = "A simple, retro theme for Hugo"
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "FOSSCELL NITC"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
      [[languages.en.menu.main]]
        identifier = "contribute"
        name = "Contribute"
        url = "/howto"
      [[languages.en.menu.main]]
        identifier = "people"
        name = "People"
        url = "/people"
